# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20170418_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='nombre',
            new_name='placa',
        ),
    ]
