# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20170418_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dueno',
            name='fecha_nac',
        ),
    ]
